name: Unifitv Malaysia

on:
  schedule:
    # Jam 7 pagi WIB = 00:00 UTC (WIB = UTC+7)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Untuk manual trigger

jobs:
  grab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install epg-grabber
        run: npm install -g epg-grabber

      - name: Run EPG Grabber
        run: |
          epg-grabber --channels=unifi.com.my.channels.xml --output=unifitv_malaysia.xml --days=3

      - name: Commit and push guide.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add unifitv_malaysia.xml
          git diff --staged --quiet || git commit -m "Update EPG unifitv_malaysia.xml"
          git push
